config/routes.rb
Rails.application.routes.draw do


  resources :categories, only: [:index, :show] do
    resources :articles
  end

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  validates :title, :description, :location, :price, :email, :category, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:show, :new, :create, :edit, :update]


  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = @category.articles.create(article_params)
     redirect_to category_path(@category)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to(@article.category)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to(@article.category)
  end

  private

    def article_params
      params.require(:article).permit(:title, :description, :location, :price, :email)
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<%= form_for([@category, @article]) do  |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:
      </h4>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>


<p>

  
  <%= f.label :title  %>
  <%= f.text_field :title %> <br>
  <%= f.label :description  %>
  <%= f.text_area :description %> <br>
  <%= f.label :location  %>
  <%= f.text_field :location %> <br>
  <%= f.label :price %>
  <%= f.number_field :price %> <br>

  <%= f.label :email  %>
  <%= f.text_field :email %>
  <%= f.submit %>

</p>

<% end %>

app/views/articles/edit.html.erb
<h3>Edit article</h3>
  <%= render 'form' %>

app/views/articles/new.erb
<h3>Create new article</h3>

<%= form_for([@category, @category.articles.build]) do  |f| %>
<p>
  <%= f.label :title  %>
  <%= f.text_field :title %> <br>
  <%= f.label :description  %>
  <%= f.text_area :description %> <br>
  <%= f.label :location  %>
  <%= f.text_field :location %> <br>
  <%= f.label :price %>
  <%= f.number_field :price %> <br>

  <%= f.label :email  %>
  <%= f.text_field :email %>
  <%= f.submit %>

</p>

<% end %>

app/views/articles/new.html.erb
<h3>Create new article</h3>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2> <%= @article.title %></h2>
<p> <%= @article.description%></p>
<p> <%= @article.location %></p>
<p> <%= @article.price %></p>
<p> <%= @article.email %></p>
<p> <%= link_to 'Back', category_path(@category) %></p>
<p> <%= link_to 'Edit', edit_category_article_path(@category) %></p>
<p> <%= link_to 'Destroy article', [@article.category, @article],
  method: :delete, data: {confirm: "Are you sure?"} %></p>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |cat| %>
  <p> <%= link_to cat.title, cat %> </p>
<% end %>

app/views/categories/show.html.erb
<h2> <%= @category.title %></h2>

<% @category.articles.each do |article| %>
  <p> <%= link_to article.title, category_article_path(@category, article)
   %></p>

<% end %>

<p> <%= link_to 'Back', categories_path %></p>
<p> <%= link_to 'Create new article', new_category_article_path(@category) %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigsJr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>